name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.RESUME_UPDATE_TOKEN }}
        gist_id: 6011527b7f2e5af1e6634b63a15bfc70
        file_path: resume.json